version: '3'

services: 

    web_server:
        image: nginx:1.17.5-alpine
        ports: 
            - "8080:80"
        volumes: 
            - ./public:/app/public
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - php_nginx
        depends_on: 
            - php

    php:
        build: 
            context: .
            dockerfile: docker/php/Dockerfile
        volumes: 
            - ./public:/app/public
        expose: 
            - 9000
        networks: 
            - php_nginx
        depends_on: 
            - db

    db:
        container_name: php_nginx_mysql
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - php_nginx_data:/var/lib/mysql
        networks: 
            - php_nginx
        environment: 
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        ports: 
            - 6033:3306

networks: 
    php_nginx:
volumes: 
    php_nginx_data: